<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>CRIM250 Assignment</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Hanzhao(Grant/Kangaroo) Kuang</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="CRIM250-Assignment.html">CRIM250 Assignment</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">CRIM250 Assignment</h1>

</div>


<div id="assignment-1" class="section level1">
<h1>Assignment 1</h1>
<p><strong>Collaborators: Lorem Ipsum. </strong></p>
<p>This assignment is due on Canvas on Monday 9/20 before class, at 10:15 am. Include the name of anyone with whom you collaborated at the top of the assignment.</p>
<div id="problem-1" class="section level3">
<h3>Problem 1</h3>
<p>Install the datasets package on the console below using <code>install.packages("datasets")</code>. Now load the library.</p>
<pre class="r"><code>#install.packages(&quot;datasets&quot;)
library(datasets)</code></pre>
<p><em>Answer</em>: Line51 install the package(I#it out because it only need to be done once). Line52 load the library.</p>
<p>Load the USArrests dataset and rename it <code>dat</code>. Note that this dataset comes with R, in the package datasets, so there’s no need to load data from your computer. Why is it useful to rename the dataset?</p>
<pre class="r"><code># This line load the USArrests dataset and rename it `dat`
dat &lt;- USArrests</code></pre>
<p><em>Answer</em>: It is important to rename the dataset for the following reasons: 1. It save time typing a long name. 2. It avoid contaminating the data so that the data is replicable.</p>
</div>
<div id="problem-2" class="section level3">
<h3>Problem 2</h3>
<p>Use this command to make the state names into a new variable called State.</p>
<pre class="r"><code>dat$state &lt;- tolower(rownames(USArrests))</code></pre>
<p>This dataset has the state names as row names, so we just want to make them into a new variable. We also make them all lower case, because that will help us draw a map later - the map function requires the states to be lower case.</p>
<p>List the variables contained in the dataset <code>USArrests</code>.</p>
<pre class="r"><code># I think both of them work as they produce the same results but with different sequences.
names(dat)</code></pre>
<pre><code>## [1] &quot;Murder&quot;   &quot;Assault&quot;  &quot;UrbanPop&quot; &quot;Rape&quot;     &quot;state&quot;</code></pre>
<pre class="r"><code>ls(dat)</code></pre>
<pre><code>## [1] &quot;Assault&quot;  &quot;Murder&quot;   &quot;Rape&quot;     &quot;state&quot;    &quot;UrbanPop&quot;</code></pre>
<p>Answer: “Assault”, “Murder”, “Rape”, “state”, and “UrbanPop”.</p>
</div>
<div id="problem-3" class="section level3">
<h3>Problem 3</h3>
<p>What type of variable (from the DVB chapter) is <code>Murder</code>?</p>
<p>Answer: Quantitative variable</p>
<p>What R Type of variable is it?</p>
<p>Answer: Numeric(as indicated in the Format part of the description of the dataset)</p>
</div>
<div id="problem-4" class="section level3">
<h3>Problem 4</h3>
<p>What information is contained in this dataset, in general? What do the numbers mean?</p>
<p>Answer: The dataset contains the statistic of the violent crime rate of 3 different kinds of crime in the 50 US States in 1973. It also contains the percentage of urban population in these states. The number means the number of arrests per 100000 people for murder, rape, and assault. The number also means percentage urban population for UrbanPop.</p>
</div>
<div id="problem-5" class="section level3">
<h3>Problem 5</h3>
<p>Draw a histogram of <code>Murder</code> with proper labels and title.</p>
<pre class="r"><code>hist(dat$Murder, main=&quot;US Murder&quot;, xlab=&quot;Murder/100000 residents&quot;, ylab=&quot;States&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="problem-6" class="section level3">
<h3>Problem 6</h3>
<p>Please summarize <code>Murder</code> quantitatively. What are its mean and median? What is the difference between mean and median? What is a quartile, and why do you think R gives you the 1st Qu. and 3rd Qu.?</p>
<pre class="r"><code>summary(dat$Murder)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.800   4.075   7.250   7.788  11.250  17.400</code></pre>
<p>Answer: The Mean is 7.788 and the Medium 7.250. THe difference between mean and median is 0.538. A quartile is one of the four parts that the data is divided into, and ithe data must be arranged from smallest to largest. R give me 1st Qu. and 3rd Qu. becasue it provides me information of the distribution and the shape of the data.</p>
</div>
<div id="problem-7" class="section level3">
<h3>Problem 7</h3>
<p>Repeat the same steps you followed for <code>Murder</code>, for the variables <code>Assault</code> and <code>Rape</code>. Now plot all three histograms toghether. You can do this by using the command <code>par(mfrow=c(3,1))</code> and then plotting each of the three.</p>
<pre class="r"><code>par(mfrow=c(3,1))
hist(dat$Murder, main=&quot;US Murder&quot;, xlab=&quot;Murder/100000 residents&quot;, ylab=&quot;States&quot;)

hist(dat$Assault, main=&quot;US Assault&quot;, xlab=&quot;Assault/100000 residents&quot;, ylab=&quot;States&quot;)

hist(dat$Rape, main=&quot;US Rape&quot;, xlab=&quot;Rape/100000 residents&quot;, ylab=&quot;States&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-7-1.png" width="480" /></p>
<p>What does the command par do, in your own words (you can look this up by asking R <code>?par</code>)?</p>
<p>Answer: The Command par set the graphical parameters for the histogram that I just plotted. It set the graph to be draw in a three row and one column setting.</p>
<p>What can you learn from plotting the histograms together?</p>
<p>Answer:We can compare the shape of the histograms to find the difference of the overall trend. We can also compare the max and min more visually. We can also have a direct representation that is more clear than a chart with numbers.</p>
</div>
<div id="problem-8" class="section level3">
<h3>Problem 8</h3>
<p>In the console below (not in text), type <code>install.packages("maps")</code> and press Enter, and then type <code>install.packages("ggplot2")</code> and press Enter. This will install the packages so you can load the libraries.</p>
<p>Run this code:</p>
<pre class="r"><code>#install.packages(&quot;maps&quot;)
#install.packages(&quot;ggplot2&quot;)
library(&#39;maps&#39;) 
library(&#39;ggplot2&#39;) 

ggplot(dat, aes(map_id=state, fill=Murder)) + 
  geom_map(map=map_data(&quot;state&quot;)) + 
  expand_limits(x=map_data(&quot;state&quot;)$long, y=map_data(&quot;state&quot;)$lat)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-8-1.png" width="720" /></p>
<p>What does this code do? Explain what each line is doing.</p>
<p>Answer: The first line construct an aesthetic mapping from the dataset “dat” with the map id being state and each state is filled with the data “Murder”.The second assign map data of variable “state” to the annotation of geom_map. The next two lines expand the plot’s limit using the data from the variable “state” for its x and y axis.</p>
</div>
</div>
<div id="assignment-2" class="section level1">
<h1>Assignment 2</h1>
<p>Instructions: Copy your code, paste it into a Word document, and turn it into Canvas. You can turn in a .docx or .pdf file. Show any EDA (graphical or non-graphical) you have used to come to this conclusion.</p>
<div id="problem-1-load-data" class="section level3">
<h3>Problem 1: Load data</h3>
<p>Set your working directory to the folder where you downloaded the data.</p>
<p>Answer:Select dat.nsduh.small.1.csv from the file on the bottomright and import the dataset.</p>
<p>Read the data</p>
<pre class="r"><code>library(readr)
dat&lt;- read_csv(&quot;dat.nsduh.small.1.csv&quot;)</code></pre>
<p>What are the dimensions of the dataset?</p>
<pre class="r"><code>names(dat) </code></pre>
<pre><code>## [1] &quot;mjage&quot;     &quot;cigage&quot;    &quot;iralcage&quot;  &quot;age2&quot;      &quot;sexatract&quot; &quot;speakengl&quot;
## [7] &quot;irsex&quot;</code></pre>
<p>Answer:The dataset has two dimensions. The first dimension is the 171 observations, and the second dimension is the 7 variables “mjage”, “cigage”, “iralcage”, “age2”, “sexatract” “speakengl” “irsex”.</p>
<p>###Problem 2: Variables Describe the variables in the dataset.</p>
<pre class="r"><code>summary(dat)</code></pre>
<pre><code>##      mjage           cigage         iralcage          age2      
##  Min.   : 7.00   Min.   :10.00   Min.   : 5.00   Min.   : 4.00  
##  1st Qu.:14.00   1st Qu.:15.00   1st Qu.:13.00   1st Qu.:13.00  
##  Median :16.00   Median :17.00   Median :15.00   Median :15.00  
##  Mean   :15.99   Mean   :17.65   Mean   :14.95   Mean   :13.98  
##  3rd Qu.:17.50   3rd Qu.:19.00   3rd Qu.:17.00   3rd Qu.:15.00  
##  Max.   :35.00   Max.   :50.00   Max.   :23.00   Max.   :17.00  
##    sexatract       speakengl        irsex      
##  Min.   : 1.00   Min.   :1.00   Min.   :1.000  
##  1st Qu.: 1.00   1st Qu.:1.00   1st Qu.:1.000  
##  Median : 1.00   Median :1.00   Median :1.000  
##  Mean   : 3.07   Mean   :1.07   Mean   :1.468  
##  3rd Qu.: 1.00   3rd Qu.:1.00   3rd Qu.:2.000  
##  Max.   :99.00   Max.   :3.00   Max.   :2.000</code></pre>
<p>Answer: The variablesin the dataset all all numeric variables in R. mjage, cigage, iralcage, and age2 are quantitative variables, and sexatract, speakengl, and irsex are categorical variables.</p>
<p>What is this dataset about? Who collected the data, what kind of sample is it, and what was the purpose of generating the data?</p>
<p>Answer:This dataset is about the national drug use of United States in 2019. The data is collected by NSDUH which directed by Substance Abuse and Mental Health Services Administration of United States. The purpose of generating these data is to monitor the usage of drugs and support prevention and treatment programs.</p>
</div>
<div id="problem-3-age-and-gender" class="section level3">
<h3>Problem 3: Age and gender</h3>
<p>What is the age distribution of the sample like? Make sure you read the codebook to know what the variable values mean.</p>
<pre class="r"><code>summary(dat$age2)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    4.00   13.00   15.00   13.98   15.00   17.00</code></pre>
<pre class="r"><code>hist(dat$age2,xlab=&quot;age&quot;, ylab=&quot;counts&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Answer: The ages of the survey range from 15 years old to 65 years old or older. The data is largely skewed to the left with a peak at the respondent group of 35-49 years old.</p>
<p>Do you think this age distribution representative of the US population? Why or why not?</p>
<p>Answer: I don’t think this age distribution is representative. First, this survey doesn’t include any people whose age is younger than 12, and that doesn’t represent U.S. population. Also, since this survey is used to monitor drug uses, their sampling method might not be random and thus not represetative of the U.S. population.</p>
<p>Is the sample balanced in terms of gender? If not, are there more females or males?</p>
<pre class="r"><code>summary(dat$irsex)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   1.000   1.468   2.000   2.000</code></pre>
<p>Answer: The sampling is not balanced in term of gender. There are more males than females.</p>
<p>Use this code to draw a stacked bar plot to view the relationship between sex and age. What can you conclude from this plot?</p>
<pre class="r"><code>tab.agesex &lt;- table(dat$irsex, dat$age2)
rownames(tab.agesex) &lt;- c(&quot;Male&quot;, &quot;Female&quot;)
barplot(tab.agesex,
        main = &quot;Distribution of Age by gender&quot;,
        xlab = &quot;Age category&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.agesex),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Answer: We can conclude from the graph that in younger population, more females are in the survey than males, but in older populations, more males are in the survey tha females. Most importantly, there are roughly the same numbers of males and females in age category 15 which is the biggest category.</p>
</div>
<div id="problem-4-substance-use" class="section level3">
<h3>Problem 4: Substance use</h3>
<p>For which of the three substances included in the dataset (marijuana, alcohol, and cigarettes) do individuals tend to use the substance earlier?</p>
<pre class="r"><code>par(mfrow=c(3,1))
hist(dat$mjage,xlab=&quot;age/mj&quot;, ylab=&quot;counts&quot;, xlim=c(0,50))
hist(dat$cigage,xlab=&quot;age/cig&quot;, ylab=&quot;counts&quot;, xlim=c(0,50))
hist(dat$iralcage,xlab=&quot;age/al&quot;, ylab=&quot;counts&quot;, xlim=c(0,50))</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Answer: According to the data, it seems that people tend to use alcohol earlier because the youngest alcohol user is at age 5, and the mean and median of alcohol usage is the lowest among the three drugs.</p>
</div>
<div id="problem-5-sexual-attraction" class="section level3">
<h3>Problem 5: Sexual attraction</h3>
<p>What does the distribution of sexual attraction look like? Is this what you expected?</p>
<pre class="r"><code>dat$sexatract.no.nas &lt;- ifelse(dat$sexatract==99, NA, dat$sexatract)
tab.sexatract &lt;- table(dat$sexatract.no.nas)
rownames(tab.sexatract) &lt;- c(&quot;Only Opposite&quot;, &quot;Mostly Opposite&quot;, &quot;Equal&quot;,&quot;Mostly Same&quot;,&quot;Only Same&quot;,&quot;Not Sure&quot;)
barplot(tab.sexatract,xlab=&quot;sex&quot;, ylab=&quot;counts&quot;, lengend=TRUE)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-16-1.png" width="960" /></p>
<p>Answer: The distribution of the sexual attraction is strongly skewed to the left. This is expected because sexual attraction to the same sex is still minority in the society, and people might not feel comfortable to disclose their sexual orientation if they are the minorities in the survey.</p>
<p>What is the distribution of sexual attraction by gender?</p>
<pre class="r"><code>par(mfrow=c(2,1))
dat.onlyfemale &lt;- dat[dat$irsex==2,]
tab.onlyfemale &lt;- table(dat.onlyfemale$sexatract.no.nas)
rownames(tab.onlyfemale) &lt;- c(&quot;Only Opposite&quot;, &quot;Mostly Opposite&quot;, &quot;Equal&quot;,&quot;Mostly Same&quot;,&quot;Only Same&quot;)
barplot(tab.onlyfemale,xlab =&quot;Sexual Attraction of Females&quot;, ylab =&quot;counts&quot;)
dat.onlymale &lt;- dat[dat$irsex==1,]
tab.onlymale &lt;- table(dat.onlymale$sexatract.no.nas)
rownames(tab.onlymale) &lt;- c(&quot;Only Opposite&quot;, &quot;Mostly Opposite&quot;,&quot;Mostly Same&quot;,&quot;Only Same&quot;,&quot;Not Sure&quot;)
barplot(tab.onlymale,xlab=&quot;Sexual Attraction of Males&quot;, ylab=&quot;counts&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-17-1.png" width="960" /></p>
<p>Answer: It is clear that for both gender the graph is strongly skewed to the right, but the for males it is more skewed than for females. That means homosexuality is minority in both cases, but there are percentage of homosexual males than females.</p>
</div>
<div id="problem-6-english-speaking" class="section level3">
<h3>Problem 6: English speaking</h3>
<p>What does the distribution of English speaking look like in the sample? Is this what you might expect for a random sample of the US population?</p>
<pre class="r"><code>summary(dat$speakengl)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    1.00    1.00    1.07    1.00    3.00</code></pre>
<pre class="r"><code>tab.speakengl &lt;- table(dat$speakengl)
rownames(tab.speakengl) &lt;- c(&quot;Very well&quot;, &quot;Well&quot;, &quot;Not Well&quot;)
barplot(tab.speakengl,xlab=&quot;English Ability&quot;, ylab=&quot;counts&quot;, legend=TRUE)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Answer: The distribution is strongly skewed to the right with a peak at 1. This means that the majority of the participants speak English very well. Given the fact that it is in the U.S., this is what I would expect from a simple random sample of U.S. population.</p>
<p>Are there more English speaker females or males?</p>
<pre class="r"><code>library(ggplot2)
gender.labs &lt;- c(`1`=&quot;Male&quot;, `2`=&quot;Female&quot;)
ggplot(data=dat, aes(x=speakengl))+
  geom_bar(na.rm=TRUE)+
  facet_grid(irsex ~ ., labeller=as_labeller(gender.labs))+
  labs(title=&quot;Distribution of English ability by gender&quot;, y=&quot;Frequency&quot;)+
  scale_x_discrete(name =&quot;English ability&quot;,
                     limits=c(&quot;Very well&quot;,&quot;Well&quot;,&quot;Not well&quot;,&quot;Not at all&quot;))</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Answer: There are more English speaking males than females.</p>
</div>
</div>
<div id="exam-1" class="section level1">
<h1>Exam 1</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<ol style="list-style-type: lower-alpha">
<li><p>Create a folder in your computer (a good place would be under Crim 250, Exams).</p></li>
<li><p>Download the dataset from the Canvas website (fatal-police-shootings-data.csv) onto that folder, and save your Exam 1.Rmd file in the same folder.</p></li>
<li><p>Download the README.md file. This is the codebook.</p></li>
<li><p>Load the data into an R data frame.</p></li>
</ol>
<pre class="r"><code>library(readr)
fatal_police_shootings_data &lt;- read_csv(&quot;C:/Users/Gluttonous Kangaroo/Desktop/Penn Works/CRIM 250/Exam/fatal-police-shootings-data.csv&quot;)
dat &lt;- fatal_police_shootings_data</code></pre>
<div id="problem-1-10-points" class="section level3">
<h3>Problem 1 (10 points)</h3>
<ol style="list-style-type: lower-alpha">
<li>Describe the dataset. This is the source: <a href="https://github.com/washingtonpost/data-police-shootings" class="uri">https://github.com/washingtonpost/data-police-shootings</a> . Write two sentences (max.) about this.</li>
</ol>
<p>Answer: This is a dataset by Washington Post which contains records of every fatal shooting in the United States by a police officer who is in the line of duty since Jan. 1, 2015.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>How many observations are there in the data frame?</li>
</ol>
<pre class="r"><code>#Look at the dat data frame on the right under the option of Environment.</code></pre>
<p>Answer: There are 6594 observations in the dataframe</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Look at the names of the variables in the data frame. Describe what “body_camera”, “flee”, and “armed” represent, according to the codebook. Again, only write one sentence (max) per variable.</li>
</ol>
<pre class="r"><code>summary(dat)</code></pre>
<pre><code>##        id           name                date            manner_of_death   
##  Min.   :   3   Length:6594        Min.   :2015-01-02   Length:6594       
##  1st Qu.:1860   Class :character   1st Qu.:2016-09-01   Class :character  
##  Median :3662   Mode  :character   Median :2018-04-21   Mode  :character  
##  Mean   :3651                      Mean   :2018-05-05                     
##  3rd Qu.:5437                      3rd Qu.:2020-01-06                     
##  Max.   :7194                      Max.   :2021-09-25                     
##                                                                           
##     armed                age           gender              race          
##  Length:6594        Min.   : 6.00   Length:6594        Length:6594       
##  Class :character   1st Qu.:27.00   Class :character   Class :character  
##  Mode  :character   Median :35.00   Mode  :character   Mode  :character  
##                     Mean   :37.12                                        
##                     3rd Qu.:45.00                                        
##                     Max.   :91.00                                        
##                     NA&#39;s   :308                                          
##      city              state           signs_of_mental_illness
##  Length:6594        Length:6594        Mode :logical          
##  Class :character   Class :character   FALSE:5100             
##  Mode  :character   Mode  :character   TRUE :1494             
##                                                               
##                                                               
##                                                               
##                                                               
##  threat_level           flee           body_camera       longitude      
##  Length:6594        Length:6594        Mode :logical   Min.   :-160.01  
##  Class :character   Class :character   FALSE:5684      1st Qu.:-112.09  
##  Mode  :character   Mode  :character   TRUE :910       Median : -94.31  
##                                                        Mean   : -97.16  
##                                                        3rd Qu.: -83.12  
##                                                        Max.   : -67.87  
##                                                        NA&#39;s   :314      
##     latitude     is_geocoding_exact
##  Min.   :19.50   Mode :logical     
##  1st Qu.:33.48   FALSE:18          
##  Median :36.09   TRUE :6576        
##  Mean   :36.66                     
##  3rd Qu.:40.00                     
##  Max.   :71.30                     
##  NA&#39;s   :314</code></pre>
<p>Answer: body_camera is a categorical and logical variable that represent whether the police wear a body camera in that observation. flee is a categorical and character variable that represent whether the victim was moving away from the officer(if the victim flee, it can be done in the means of foot or car). Armed is a categorical and character varialbe that represent whether the victim equipped some level of arm that could inflict harm(status can be armed(with indication of weapons)/undetermined/unknown/unarmed)</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What are three weapons that you are surprised to find in the “armed” variable? Make a table of the values in “armed” to see the options.</li>
</ol>
<pre class="r"><code>tab.arm &lt;-table(dat$armed)</code></pre>
<p>Answer: Air conditioner, microphone, and fire work are suprising for me to see that can be used as weapon. I think either the victims were very creative or the police officers were making misjudgements.</p>
</div>
<div id="problem-2-10-points" class="section level3">
<h3>Problem 2 (10 points)</h3>
<ol style="list-style-type: lower-alpha">
<li>Describe the age distribution of the sample. Is this what you would expect to see?</li>
</ol>
<pre class="r"><code>hist(dat$age,xlab=&quot;age&quot;, ylab=&quot;counts&quot;, xlim=c(0,100))</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Answer: The distribution is strongly skewed to the right with one mode around age 30. This means that a large portion of the victims are adults in their mid ages. This is what I am expected to see because the police officers are more likely to see the mid age adults as potential dangers rather than children or old people.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>To understand the center of the age distribution, would you use a mean or a median, and why? Find the one you picked.</li>
</ol>
<pre class="r"><code>#Look at the age variable in summary(dat).
summary(dat)</code></pre>
<pre><code>##        id           name                date            manner_of_death   
##  Min.   :   3   Length:6594        Min.   :2015-01-02   Length:6594       
##  1st Qu.:1860   Class :character   1st Qu.:2016-09-01   Class :character  
##  Median :3662   Mode  :character   Median :2018-04-21   Mode  :character  
##  Mean   :3651                      Mean   :2018-05-05                     
##  3rd Qu.:5437                      3rd Qu.:2020-01-06                     
##  Max.   :7194                      Max.   :2021-09-25                     
##                                                                           
##     armed                age           gender              race          
##  Length:6594        Min.   : 6.00   Length:6594        Length:6594       
##  Class :character   1st Qu.:27.00   Class :character   Class :character  
##  Mode  :character   Median :35.00   Mode  :character   Mode  :character  
##                     Mean   :37.12                                        
##                     3rd Qu.:45.00                                        
##                     Max.   :91.00                                        
##                     NA&#39;s   :308                                          
##      city              state           signs_of_mental_illness
##  Length:6594        Length:6594        Mode :logical          
##  Class :character   Class :character   FALSE:5100             
##  Mode  :character   Mode  :character   TRUE :1494             
##                                                               
##                                                               
##                                                               
##                                                               
##  threat_level           flee           body_camera       longitude      
##  Length:6594        Length:6594        Mode :logical   Min.   :-160.01  
##  Class :character   Class :character   FALSE:5684      1st Qu.:-112.09  
##  Mode  :character   Mode  :character   TRUE :910       Median : -94.31  
##                                                        Mean   : -97.16  
##                                                        3rd Qu.: -83.12  
##                                                        Max.   : -67.87  
##                                                        NA&#39;s   :314      
##     latitude     is_geocoding_exact
##  Min.   :19.50   Mode :logical     
##  1st Qu.:33.48   FALSE:18          
##  Median :36.09   TRUE :6576        
##  Mean   :36.66                     
##  3rd Qu.:40.00                     
##  Max.   :71.30                     
##  NA&#39;s   :314</code></pre>
<p>Answer: I would choose median instead of the mean mainly because there are extreme values from both side(A min for age of 6 and a max for age of 91) that can influence the distribution. Median is resistant to extreme values which is a better choice in this case. The median of age is 35.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Describe the gender distribution of the sample. Do you find this surprising?</li>
</ol>
<pre class="r"><code>tab.gender &lt;- table(dat$gender)
barplot(tab.gender,xlab=&quot;gender&quot;, ylab=&quot;counts&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Answer: The gender distribution overwhelmingly unbalanced with the vast majority of the victim being males than females. In fact, the male victims are 20 times more than the female victims. I don’t find this surprising because it is reasonable for a police officer to find a male with higher potential danger than a female.</p>
</div>
<div id="problem-3-10-points" class="section level3">
<h3>Problem 3 (10 points)</h3>
<ol style="list-style-type: lower-alpha">
<li>How many police officers had a body camera, according to news reports? What proportion is this of all the incidents in the data? Are you surprised that it is so high or low?</li>
</ol>
<pre class="r"><code>tab.bodycamera &lt;- table(dat$body_camera)
barplot(tab.bodycamera,xlab=&quot;bodycamera&quot;, ylab=&quot;counts&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Answer: 910 police officers had a body camera. However, it is only 910/6594=13.8% of all observations. I am not surprised that the body camera rate is so low because implementing a body camera for every officer can be costly, so some underfunded police apartments which located in more poor or chaotic areas (probably more shooting incidents) might not equip their officers to save money.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>In how many of the incidents was the victim fleeing? What proportion is this of the total number of incidents in the data? Is this what you would expect?</li>
</ol>
<pre class="r"><code>tab.flee &lt;- table(dat$flee)
barplot(tab.flee,xlab=&quot;flee&quot;, ylab=&quot;counts&quot;)</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Answer:1058 of the victims flee on foot and 845 of the victims flee on car, which is 1903/6594=28.9% of the observations. This is unexpected because fleeing is usually involved with a chase and the whole process accelerate the tension of the situation. More tension is very likely to be a cause for more fatal shooting, so I am surprised by the fact that less than 30% of the victims did flee. However, in order to get the holistic picture, we must combine the variable threat level into the consideration.</p>
</div>
<div id="problem-4-10-points---answer-only-one-of-these-a-or-b." class="section level3">
<h3>Problem 4 (10 points) - Answer only one of these (a or b).</h3>
<ol style="list-style-type: lower-alpha">
<li>Describe the relationship between the variables “body camera” and “flee” using a stacked barplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the options for “flee”, each bar contains information about whether the police officer had a body camera (vertically), and the height along the y-axis shows the frequency of that category).</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for barplot, run ?barplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<p><strong>Your answer here.</strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Describe the relationship between age and race by using a boxplot. What can you conclude from this relationship?</li>
</ol>
<p><em>Hint 1: The categories along the x-axis are the race categories and the height along the y-axis is age.</em></p>
<p><em>Hint 2: Also, if you are unsure about the syntax for boxplot, run ?boxplot in R and see some examples at the bottom of the documentation. This is usually a good way to look up the syntax of R code. You can also Google it.</em></p>
<pre class="r"><code>plot(factor(dat$race), dat$age, ylab=&quot;age&quot;, xlab=&quot;Race&quot;, names=c(&quot;Asian&quot;,&quot;Black&quot;,&quot;Hispanic&quot;,&quot;Native A&quot;,&quot;Other&quot;,&quot;White&quot;))</code></pre>
<p><img src="CRIM250-Assignment_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Answer: There is no straightforward correlation between age and race. However, it seems that the White victims have more spread than all the minority group victims. This means that there are White victims from all ages being shot. On the other hand, the minority groups victims are younger and more concentrated(they have less inter-quartile range and a smaller median). Also, there are many outliers of the White victims that are very old.</p>
</div>
<div id="extra-credit-10-points" class="section level3">
<h3>Extra credit (10 points)</h3>
<ol style="list-style-type: lower-alpha">
<li>What does this code tell us?</li>
</ol>
<pre class="r"><code>mydates &lt;- as.Date(dat$date)
head(mydates)
(mydates[length(mydates)] - mydates[1])</code></pre>
<p>Answer: This code tell us the time difference of 2458 days. It tells us the length of the list that is given by date.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>On Friday, a new report was published that was described as follows by The Guardian: “More than half of US police killings are mislabelled or not reported, study finds.” Without reading this article now (due to limited time), why do you think police killings might be mislabelled or underreported?</li>
</ol>
<p>Answer: One of the key reason is that underreport can avoild the public’s focus on police brutality which give the police department less pressure.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Regarding missing values in problem 4, do you see any? If so, do you think that’s all that’s missing from the data?</li>
</ol>
<p>Answer: Yes there are missing values. I don’t think that is all missing from the data because some of the data might not even be reported in the dataset.</p>
<p><span class="math display">\[\\[2in]\]</span></p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
